"""add: deleted user

Revision ID: 2f92e61e64f0
Revises: 31a6ea853698
Create Date: 2026-02-09 15:05:24.303652

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f92e61e64f0"
down_revision: Union[str, Sequence[str], None] = "31a6ea853698"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", existing_type=sa.String(length=255), nullable=True)
    op.add_column("user", sa.Column("is_deleted", sa.Boolean(), nullable=False))
    op.add_column(
        "user", sa.Column("deleted_email", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "deleted_email")
    op.drop_column("user", "is_deleted")
    op.alter_column("user", "email", existing_type=sa.String(length=255), nullable=False)
    # ### end Alembic commands ###
