"""add search, device, like

Revision ID: 31a6ea853698
Revises: 2b4d5e0385e4
Create Date: 2026-01-30 12:30:09.301687

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "31a6ea853698"
down_revision: Union[str, Sequence[str], None] = "2b4d5e0385e4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("user_agent", sa.String(length=255), nullable=False),
        sa.Column("last_active", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_searches",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("term", sa.String(length=50), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "likes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("post_id", sa.BigInteger(), nullable=False),
        sa.Column("device_id", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("comment", sa.Column("media_id", sa.BigInteger(), nullable=False))
    op.alter_column("comment", "user_id", existing_type=sa.BIGINT(), nullable=True)
    op.create_foreign_key(None, "comment", "media", ["media_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comment", type_="foreignkey")
    op.alter_column("comment", "user_id", existing_type=sa.BIGINT(), nullable=False)
    op.drop_column("comment", "media_id")
    op.drop_table("likes")
    op.drop_table("user_searches")
    op.drop_table("devices")
    # ### end Alembic commands ###
